defmodule Sudoku.Repo.Migrations.AddPuzzleGivens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:saved_puzzles) do
      add :givens, :text, null: false
    end
  end

  def down do
    alter table(:saved_puzzles) do
      remove :givens
    end
  end
end