defmodule Sudoku.Repo.Migrations.AddElapsedSeconds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:saved_puzzles) do
      add :elapsed_seconds, :bigint, null: false
    end
  end

  def down do
    alter table(:saved_puzzles) do
      remove :elapsed_seconds
    end
  end
end