defmodule Sudoku.Repo.Migrations.AddSavedPuzzles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:saved_puzzles, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :center_marks, :map, null: false, default: %{}
      add :corner_marks, :map, null: false, default: %{}
      add :cells, {:array, :map}, null: false
      add :difficulty, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:saved_puzzles, [:name], name: "saved_puzzles_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:saved_puzzles, [:name], name: "saved_puzzles_unique_name_index")

    drop table(:saved_puzzles)
  end
end